/*
 * Automatisch erzeugt von tools/update-gallery-images.sh.
 * Nicht von Hand bearbeiten - Skript neu laufen lassen.
 */
window.GALLERY_IMAGES = [
	"img/Galerie/20230707_Bild_10_slidesHD.jpg",
	"img/Galerie/20230707_Bild_8_slidesHD.jpg",
	"img/Galerie/20230707_Bild_9_slidesHD.jpg",
	"img/Galerie/20230712_Bild_28_slidesHD.jpg",
	"img/Galerie/20230712_Bild_30_slidesHD.jpg",
	"img/Galerie/20240124_Bild_10_slidesHD.jpg",
	"img/Galerie/20240124_Bild_11_slidesHD.jpg",
	"img/Galerie/20240124_Bild_12_slidesHD.jpg",
	"img/Galerie/20240124_Bild_15_slidesHD.jpg",
	"img/Galerie/20240124_Bild_18_slidesHD.jpg",
	"img/Galerie/20240124_Bild_2_slidesHD.jpg",
	"img/Galerie/20240124_Bild_22_slidesHD.jpg",
	"img/Galerie/20240124_Bild_26_slidesHD.jpg",
	"img/Galerie/20240124_Bild_28_slidesHD.jpg",
	"img/Galerie/20240124_Bild_37_slidesHD.jpg",
	"img/Galerie/20240124_Bild_38_slidesHD.jpg",
	"img/Galerie/20240124_Bild_40_slidesHD.jpg",
	"img/Galerie/20240124_Bild_7_slidesHD.jpg",
	"img/Galerie/47498-004749830003-vhBk_slidesHD.jpg",
	"img/Galerie/47498-004749830005-KyuO_slidesHD.jpg",
	"img/Galerie/Bild 10_slidesHD.jpg",
	"img/Galerie/Bild 13_1_slidesHD.jpg",
	"img/Galerie/Bild 13_slidesHD.jpg",
	"img/Galerie/Bild 14_slidesHD.jpg",
	"img/Galerie/Bild 15_slidesHD.jpg",
	"img/Galerie/Bild 16_1_slidesHD.jpg",
	"img/Galerie/Bild 16_slidesHD.jpg",
	"img/Galerie/Bild 17_slidesHD.jpg",
	"img/Galerie/Bild 18_slidesHD.jpg",
	"img/Galerie/Bild 19_slidesHD.jpg",
	"img/Galerie/Bild 21_1_slidesHD.jpg",
	"img/Galerie/Bild 21_slidesHD.jpg",
	"img/Galerie/Bild 22_1_slidesHD.jpg",
	"img/Galerie/Bild 22_slidesHD.jpg",
	"img/Galerie/Bild 23_1_slidesHD.jpg",
	"img/Galerie/Bild 23_slidesHD.jpg",
	"img/Galerie/Bild 26_slidesHD.jpg",
	"img/Galerie/Bild 29_slidesHD.jpg",
	"img/Galerie/Bild 31_slidesHD.jpg",
	"img/Galerie/Bild 32_slidesHD.jpg",
	"img/Galerie/Bild 33_1_slidesHD.jpg",
	"img/Galerie/Bild 33_slidesHD.jpg",
	"img/Galerie/Bild 35_slidesHD.jpg",
	"img/Galerie/Bild 6_slidesHD.jpg",
	"img/Galerie/Bild 7_1_slidesHD.jpg",
	"img/Galerie/Bild 7_slidesHD.jpg",
	"img/Galerie/Bild 8_1_slidesHD.jpg",
	"img/Galerie/Bild 8_2_slidesHD.jpg",
	"img/Galerie/Bild 8_3_slidesHD.jpg",
	"img/Galerie/Bild 8_slidesHD.jpg",
	"img/Galerie/Bild 9_slidesHD.jpg",
	"img/Galerie/Bild_1_1_slidesHD.jpg",
	"img/Galerie/Bild_1_slidesHD.jpg",
	"img/Galerie/Bild_10_1_slidesHD.jpg",
	"img/Galerie/Bild_10_2_slidesHD.jpg",
	"img/Galerie/Bild_10_slidesHD.jpg",
	"img/Galerie/Bild_11_1_slidesHD.jpg",
	"img/Galerie/Bild_11_slidesHD.jpg",
	"img/Galerie/Bild_13_1_slidesHD.jpg",
	"img/Galerie/Bild_13_slidesHD.jpg",
	"img/Galerie/Bild_15_slidesHD.jpg",
	"img/Galerie/Bild_16_slidesHD.jpg",
	"img/Galerie/Bild_18_1_slidesHD.jpg",
	"img/Galerie/Bild_18_slidesHD.jpg",
	"img/Galerie/Bild_19_1_slidesHD.jpg",
	"img/Galerie/Bild_19_slidesHD.jpg",
	"img/Galerie/Bild_2_slidesHD.jpg",
	"img/Galerie/Bild_20_1_slidesHD.jpg",
	"img/Galerie/Bild_20_2_slidesHD.jpg",
	"img/Galerie/Bild_20_slidesHD.jpg",
	"img/Galerie/Bild_22_slidesHD.jpg",
	"img/Galerie/Bild_24_slidesHD.jpg",
	"img/Galerie/Bild_26_slidesHD.jpg",
	"img/Galerie/Bild_27_1_slidesHD.jpg",
	"img/Galerie/Bild_27_slidesHD.jpg",
	"img/Galerie/Bild_29_1_slidesHD.jpg",
	"img/Galerie/Bild_29_slidesHD.jpg",
	"img/Galerie/Bild_3_slidesHD.jpg",
	"img/Galerie/Bild_32_1_slidesHD.jpg",
	"img/Galerie/Bild_32_slidesHD.jpg",
	"img/Galerie/Bild_33_slidesHD.jpg",
	"img/Galerie/Bild_35_slidesHD.jpg",
	"img/Galerie/Bild_36_slidesHD.jpg",
	"img/Galerie/Bild_38_slidesHD.jpg",
	"img/Galerie/Bild_4_1_slidesHD.jpg",
	"img/Galerie/Bild_4_slidesHD.jpg",
	"img/Galerie/Bild_40_slidesHD.jpg",
	"img/Galerie/Bild_7_1_slidesHD.jpg",
	"img/Galerie/Bild_7_slidesHD.jpg",
	"img/Galerie/Bild_8_1_slidesHD.jpg",
	"img/Galerie/Bild_8_2_slidesHD.jpg",
	"img/Galerie/Bild_8_slidesHD.jpg",
	"img/Galerie/Bild_9_1_slidesHD.jpg",
	"img/Galerie/Bild_9_slidesHD.jpg",
	"img/Galerie/DSC_0267_slidesHD.jpg",
	"img/Galerie/DSC_0293_slidesHD.jpg",
	"img/Galerie/HEKA2058_slidesHD.jpg",
	"img/Galerie/HEKA2060_slidesHD.jpg",
	"img/Galerie/HEKA2063_slidesHD.jpg",
	"img/Galerie/HEKA2064_slidesHD.jpg",
	"img/Galerie/HEKA2065_slidesHD.jpg",
	"img/Galerie/HEKA2071_slidesHD.jpg",
	"img/Galerie/HEKA2073_slidesHD.jpg",
	"img/Galerie/HEKA2075_slidesHD.jpg",
	"img/Galerie/HEKA2079_slidesHD.jpg",
	"img/Galerie/HEKA2083_slidesHD.jpg",
	"img/Galerie/HEKA2088_slidesHD.jpg",
	"img/Galerie/HEKA2093_slidesHD.jpg",
	"img/Galerie/HEKA2097_slidesHD.jpg",
	"img/Galerie/HEKA2102_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_1_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_23_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_26_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_27_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_28_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_29_slidesHD.jpg",
	"img/Galerie/Honberg_Bild_4_slidesHD.jpg",
	"img/Galerie/Mettnau_Bild_11_slidesHD.jpg",
	"img/Galerie/Mettnau_Bild_12_slidesHD.jpg",
	"img/Galerie/Mettnau_Bild_14_slidesHD.jpg",
	"img/Galerie/R1-01717-0032_slidesHD.jpg",
	"img/Galerie/R1-01718-0005_slidesHD.jpg",
	"img/Galerie/R1-01969-0033_slidesHD.jpg",
	"img/Galerie/R1-01969-0034_slidesHD.jpg",
	"img/Galerie/R1-01969-0036_slidesHD.jpg",
	"img/Galerie/Spaichingen_Bild_31_slidesHD.jpg",
	"img/Galerie/Spaichingen_Bild_32_slidesHD.jpg",
	"img/Galerie/Spaichingen_Bild_33_slidesHD.jpg",
	"img/Galerie/Spaichingen_Bild_5_slidesHD.jpg",
];
